quarkus:
  datasource:
  db-kind: postgresql
  username: postgres
  password: postgres
  reactive:
    url: jdbc:postgresql://localhost:5432/postgres
    max-size=: 0
  hibernate-orm:
    database:
      generation: drop-and-create