spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

feign:
  httpclient:
    disable-ssl-validation: true
  autoconfiguration:
    jackson:
      enabled: true